<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Common.Dotnet.CsWinRT.props" />
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
    <ProjectReference Include="..\TmdbExtension\TmdbExtension.csproj" />
  </ItemGroup>
</Project>
